apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-b
spec:
  destination:
    namespace: team-b
    server: https://kubernetes.default.svc
  project: default
  source:
    path: edge-multi-ns-example # replace to use folder working to see it work
    repoURL: https://github.com/choejwoo/argo-cd-test.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    managedNamespaceMetadata:
      annotations:
        argocd.argoproj.io/tracking-id: team-b:apps/Namespace:team-b/team-b
    retry:
      backoff:
        duration: 1m
    syncOptions:
    - CreateNamespace=true
